services:
  recipiece_frontend:
    build:
      context: .
      dockerfile: ./recipiece_frontend/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - recipiece_backend
    volumes:
      - ./recipiece_frontend:/recipiece_frontend
      - ./recipiece_common/recipiece_types:/recipiece_common/recipiece_types
  recipiece_database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'recipiece'
      POSTGRES_DB: 'recipiece'
      POSTGRES_USER: 'recipiece'
    ports:
      - "5432:5432"
    volumes:
      - ./local-recipiece-data:/var/lib/postgresql/data
  recipiece_redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  recipiece_database_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'recipiece'
      POSTGRES_DB: 'recipiece'
      POSTGRES_USER: 'recipiece'
    ports:
      - "5433:5432"
  recipiece_backend:
    build:
      context: .
      dockerfile: ./recipiece_backend/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - recipiece_database
      - recipiece_redis
      - recipiece_recipe_importer
    volumes:
      - ./recipiece_backend:/recipiece_backend
      - ./recipiece_common:/recipiece_common
  recipiece_recipe_importer:
    build:
      context: ./recipiece_recipe_importer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./recipiece_recipe_importer:/home
