services:
  recipiece_database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: 'recipiece'
      POSTGRES_DB: 'recipiece'
      POSTGRES_USER: 'recipiece'
    ports:
      - "5432:5432"
    volumes:
      - ./recipiece_local_data/postgres:/var/lib/postgresql/data
  recipiece_redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  recipiece_database_test:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: 'recipiece'
      POSTGRES_DB: 'recipiece'
      POSTGRES_USER: 'recipiece'
    ports:
      - "5433:5432"
  s3mock:
    image: adobe/s3mock:latest
    environment:
      - initialBuckets=recipiece_dev,recipiece_test
      - retainFilesOnExit=true
      - root=s3
    ports:
      - 9090:9090
    volumes:
      - ./recipiece_local_data/s3:/s3
