version: '3.9'
services:
  recipiece_frontend:
    build:
      context: ./recipiece_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - recipiece_backend
    volumes:
      - ./recipiece_frontend:/home
  recipiece_database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'recipiece'
      POSTGRES_DB: 'recipiece'
      POSTGRES_USER: 'recipiece'
    ports:
      - "5432:5432"
    volumes:
      - ./local-recipiece-data:/var/lib/postgresql/data
  recipiece_redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  recipiece_database_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'recipiece'
      POSTGRES_DB: 'recipiece'
      POSTGRES_USER: 'recipiece'
    ports:
      - "5433:5432"
  recipiece_backend:
    build:
      context: ./recipiece_backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - recipiece_database
      - recipiece_redis
      - recipiece_recipe_importer
    volumes:
      - ./recipiece_backend:/home
    environment:
      - APP_PORT=8080
      - DATABASE_URL=postgresql://recipiece:recipiece@recipiece_database:5432/recipiece
      - REDIS_URL=redis://recipiece_redis:6379/1
      - APP_RECIPE_PARSER_SERVICE_URL=http://recipiece_recipe_importer:8081
      - APP_SECRET=339FBFBD8B9A1473989F459C5D9FB
      - APP_SEND_EMAIL=N
      - APP_EMAIL_HOST=mail.nomail.com
      - APP_EMAIL_ADDRESS=support@recipiece.org
      - APP_EMAIL_PASSWORD=nonsensePassword1234!
  recipiece_recipe_importer:
    build:
      context: ./recipiece_recipe_importer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./recipiece_recipe_importer:/home
