version: '3.9'
services:
  recipiece_database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'recipiece'
      POSTGRES_DB: 'recipiece'
      POSTGRES_USER: 'recipiece'
    ports:
      - 5432:5432
  volumes:
    - ./local-recipiece-data:/var/lib/postgresql/data
  recipiece_redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  recipiece_database_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'recipiece'
      POSTGRES_DB: 'recipiece'
      POSTGRES_USER: 'recipiece'
    ports:
      - 5433:5432

