FROM python:3.12-alpine

WORKDIR /home
COPY . .

RUN pip install --no-cache-dir --upgrade pip && pip install -r requirements.txt

CMD ["fastapi", "run", "src/main.py", "--proxy-headers", "--port", "8081"]
